name: Deploy dev

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build-dev

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: 176.123.165.162
          username: dmtr636
          key: ${{ secrets.SSH_KEY }}
          source: "dist/*"
          target: "/home/dmtr636/build-backend/cdn/frontend-dev/admin"
          rm: true